# Generated by Django 5.0.6 on 2024-05-23 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallowers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kuzatuvchilar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
